/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:894194:
  appc.background(230);
} //_CODE_:window1:894194:

public void addLiquidSliderEvent(GSlider source, GEvent event) { //_CODE_:addLiquidSlider:761355:
  println("addLiquidSlider - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:addLiquidSlider:761355:

public void shiftInputModeEvent(GButton source, GEvent event) { //_CODE_:shiftInputMode:794145:
  userInputMode = (userInputMode + 1) % 2;
  if (userInputMode == 0) {
    selectedLiquid = 1;
    blockMakerMode = false;
    currentMode.setText("Current Mode: Adding Fluid");
    
  }
  else if (userInputMode == 1) {
    selectedLiquid = 0;
    blockMakerMode = true;
    currentMode.setText("Current Mode: Adding Blocks");
  }
} //_CODE_:shiftInputMode:794145:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 240, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  addLiquidSlider = new GSlider(window1, 10, 100, 100, 40, 10.0);
  addLiquidSlider.setLimits(10, 1, 20);
  addLiquidSlider.setNumberFormat(G4P.INTEGER, 0);
  addLiquidSlider.setOpaque(false);
  addLiquidSlider.addEventHandler(this, "addLiquidSliderEvent");
  shiftInputMode = new GButton(window1, 120, 10, 80, 30);
  shiftInputMode.setText("Next");
  shiftInputMode.addEventHandler(this, "shiftInputModeEvent");
  currentMode = new GLabel(window1, 20, 5, 100, 40);
  currentMode.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  currentMode.setText("Current Mode: Adding Liquid");
  currentMode.setOpaque(false);
  liquidAddAmountLabel = new GLabel(window1, 20, 70, 80, 30);
  liquidAddAmountLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  liquidAddAmountLabel.setText("Amount of Liquid to Add");
  liquidAddAmountLabel.setOpaque(false);
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GSlider addLiquidSlider; 
GButton shiftInputMode; 
GLabel currentMode; 
GLabel liquidAddAmountLabel; 
